/**
 * Summary Writer Agent
 *
 * Phase 2 of the Daily Summary pipeline.
 *
 * This agent synthesizes research findings into a polished daily summary.
 * It has no tool access - it works purely from the ResearchContext.
 *
 * Outputs DailySummary with narrative content and structured sections.
 *
 * @module
 */

import { Effect, Schema, Clock, Data, Config, Option } from "effect"
import { LanguageModel, Chat, Prompt, Tokenizer } from "@effect/ai"
import {
  buildWriterSystemPrompt,
  buildResearchContextMessage,
  buildDataRequirementsSection,
  type DataRequirementsCounts
} from "./prompts/writer-prompt.js"
import type { ResearchContextType, DailySummaryType } from "./schemas.js"
import type { PlayLookupEntry, CategorizedPlayIds } from "./play-reference.js"
import { type TokenUsage, mutableTokenUsage } from "../multi-agent/types.js"

// =============================================================================
// Types
// =============================================================================

/**
 * Options for the write method
 */
export interface WriterOptions {
  /** Compact play lookup table for ID resolution */
  readonly playLookup?: ReadonlyArray<PlayLookupEntry>
  /** Categorized play IDs for schema population */
  readonly categorizedIds?: CategorizedPlayIds
}

/**
 * Writer agent result including metadata
 */
export interface WriterResult {
  readonly summary: DailySummaryType
  readonly durationMs: number
  readonly tokenUsage: TokenUsage
}

/**
 * Error type for writer failures
 */
export class SummaryWriterError extends Data.TaggedError("SummaryWriterError")<{
  readonly message: string
  readonly cause?: unknown
}> {}

// =============================================================================
// Output Schema for LLM
// =============================================================================

/**
 * Schema for writer output
 */
const WriterOutputSchema = Schema.Struct({
  headline: Schema.String,

  // Narrative layer - required
  openingNarrative: Schema.String,

  // All arrays are optional - LLM may omit fields
  highlights: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    playId: Schema.Number,
    headline: Schema.String,
    description: Schema.String,
    category: Schema.Literal("discovery", "theme", "cultural", "connection", "rare", "local"),
    showName: Schema.NullOr(Schema.String)
  })))),

  discoveries: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    playId: Schema.Number,
    artist: Schema.String,
    song: Schema.String,
    album: Schema.NullOr(Schema.String),
    discoveryType: Schema.Literal("first_play", "first_artist", "first_album"),
    blurb: Schema.String
  })))),

  freshReleases: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    playId: Schema.Number,
    artist: Schema.String,
    song: Schema.String,
    album: Schema.NullOr(Schema.String),
    releaseDate: Schema.NullOr(Schema.String),
    releaseType: Schema.Literal("single", "album", "ep", "compilation", "unknown"),
    isLocal: Schema.Boolean,
    blurb: Schema.String
  })))),

  rotationUpdates: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    playId: Schema.Number,
    artist: Schema.String,
    song: Schema.String,
    rotationStatus: Schema.NullOr(Schema.String),
    playCountToday: Schema.Number,
    blurb: Schema.NullOr(Schema.String)
  })))),

  themes: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    title: Schema.String,
    description: Schema.String,
    playIds: Schema.Array(Schema.Number),
    showNames: Schema.Array(Schema.String)
  })))),

  culturalMoments: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    type: Schema.Literal("birthday", "anniversary", "death", "event", "theme_day", "other"),
    title: Schema.String,
    description: Schema.String,
    playIds: Schema.Array(Schema.Number),
    source: Schema.NullOr(Schema.String)
  })))),

  // Play references - optional
  playIds: Schema.optional(Schema.NullOr(Schema.Array(Schema.Number))),
  topPickIds: Schema.optional(Schema.NullOr(Schema.Array(Schema.Number))),
  newMusicPlaylistIds: Schema.optional(Schema.NullOr(Schema.Array(Schema.Number)))

  // Note: stats are computed from research context, not generated by LLM
})

type WriterOutput = typeof WriterOutputSchema.Type

// =============================================================================
// Service Interface
// =============================================================================

export interface SummaryWriterAgentInterface {
  /**
   * Write summary from research context
   *
   * @param research - Research findings with playIds embedded
   * @param options - Optional play lookup table and categorized IDs for resolution
   */
  readonly write: (
    research: ResearchContextType,
    options?: WriterOptions
  ) => Effect.Effect<
    WriterResult,
    SummaryWriterError,
    LanguageModel.LanguageModel
  >
}

// =============================================================================
// Service Tag
// =============================================================================

export class SummaryWriterAgent extends Effect.Service<SummaryWriterAgent>()(
  "SummaryWriterAgent",
  {
    effect: Effect.gen(function* () {
      /**
       * Convert writer output to DailySummary
       *
       * Stats are computed from research context (not LLM-generated) for accuracy.
       */
      const toDailySummary = (
        output: WriterOutput,
        research: ResearchContextType
      ): DailySummaryType => ({
        date: research.date,
        headline: output.headline,

        // Narrative layer
        openingNarrative: output.openingNarrative,
        highlights: (output.highlights ?? []).map(h => ({
          ...h,
          category: h.category as "discovery" | "theme" | "cultural" | "connection" | "rare" | "local"
        })),

        // Structured sections - handle null with empty arrays
        discoveries: (output.discoveries ?? []).map(d => ({
          ...d,
          discoveryType: d.discoveryType as "first_play" | "first_artist" | "first_album"
        })),
        freshReleases: (output.freshReleases ?? []).map(r => ({
          ...r,
          releaseType: r.releaseType as "single" | "album" | "ep" | "compilation" | "unknown"
        })),
        rotationUpdates: output.rotationUpdates ?? [],
        themes: output.themes ?? [],
        culturalMoments: (output.culturalMoments ?? []).map(c => ({
          ...c,
          type: c.type as "birthday" | "anniversary" | "death" | "event" | "theme_day" | "other"
        })),

        // Play references - handle null with empty arrays/null
        playIds: output.playIds ?? [],
        topPickIds: output.topPickIds ?? [],
        newMusicPlaylistIds: output.newMusicPlaylistIds ?? [],

        // Stats - computed from research context for accuracy (not LLM-generated)
        stats: {
          totalPlays: research.totalPlays,
          uniqueArtists: research.uniqueArtists,
          uniqueAlbums: research.uniqueAlbums,
          newToKexp: research.discoveries.length, // Count of discoveries
          localArtists: research.localArtistCount,
          livePerformances: research.livePerformanceCount,
          listenerRequests: research.requestCount,
          showCount: research.showSummaries.length
        },

        // Metadata
        generatedAt: new Date().toISOString(),
        researchId: 0 // Will be set by orchestrator
      })

      const truncatePrompt = (
        prompt: Prompt.Prompt,
        maxTokens: number,
        label: string
      ): Effect.Effect<Prompt.Prompt, never> =>
        Effect.serviceOption(Tokenizer.Tokenizer).pipe(
          Effect.flatMap((tokenizerOption) =>
            maxTokens > 0
              ? Option.match(tokenizerOption, {
                  onNone: () =>
                    Effect.logWarning(`${label} prompt truncation skipped (Tokenizer unavailable)`).pipe(
                      Effect.as(prompt)
                    ),
                  onSome: (tokenizer) =>
                    tokenizer.truncate(prompt, maxTokens).pipe(
                      Effect.catchAll((error) =>
                        Effect.logWarning(
                          `${label} prompt truncation failed: ${
                            error instanceof Error ? error.message : String(error)
                          }`
                        ).pipe(Effect.as(prompt))
                      )
                    )
                })
              : Effect.succeed(prompt)
          )
        )

      const write = (
        research: ResearchContextType,
        options?: WriterOptions
      ): Effect.Effect<
        WriterResult,
        SummaryWriterError,
        LanguageModel.LanguageModel
      > =>
        Effect.gen(function* () {
          yield* Effect.log(`Starting writer for ${research.date}`)
          if (options?.playLookup) {
            yield* Effect.log(`Play lookup table: ${options.playLookup.length} plays`)
          }
          if (options?.categorizedIds) {
            yield* Effect.log(`Categorized IDs: ${options.categorizedIds.all.length} total`)
          }

          const startTime = yield* Clock.currentTimeMillis
          const maxTokens = yield* Config.number("DAILY_SUMMARY_WRITER_MAX_TOKENS").pipe(
            Config.withDefault(60000),
            Effect.catchAll(() => Effect.succeed(60000))
          )

          // Build prompt using array-based pattern (correct @effect/ai API)
          const systemPrompt = buildWriterSystemPrompt()
          const userMessage = buildResearchContextMessage(research, {
            playLookup: options?.playLookup,
            categorizedIds: options?.categorizedIds
          })

          // Build explicit playId guidance if categorized IDs are provided
          const playIdGuidance = options?.categorizedIds
            ? `
CRITICAL - PlayId Population:
The "Play ID Population Guide" section above lists ALL playIds you must include.
- playIds array: COPY ALL ${options.categorizedIds.all.length} IDs from the guide
- topPickIds: Select 5-10 from discoveries and notable plays
- newMusicPlaylistIds: COPY ALL ${options.categorizedIds.freshReleases.length} fresh release IDs

These arrays MUST NOT be empty. Use the exact IDs from the guide.`
            : ""

          // Build data requirements section with exact counts from research
          const researchCounts: DataRequirementsCounts = {
            discoveries: research.discoveries.length,
            freshReleases: research.freshReleases.length,
            rotationUpdates: research.rotationUpdates.length,
            themes: research.themes.length,
            culturalMoments: research.culturalMoments.length,
            notablePlays: research.notablePlays.length
          }
          const dataRequirements = buildDataRequirementsSection(researchCounts)

          const writerInstructions = `${userMessage}

${dataRequirements}

Write the complete daily summary as JSON. Include:
- A compelling headline (6-8 words, specific, KEXP voice)
- Opening narrative (2-3 paragraphs)
- 5-8 highlights with play IDs
- All discoveries from the research (EXACTLY ${research.discoveries.length})
- Fresh releases (EXACTLY ${research.freshReleases.length})
- Rotation updates (EXACTLY ${research.rotationUpdates.length})
- Themes with representative play IDs (EXACTLY ${research.themes.length})
- Cultural moments with associated play IDs (EXACTLY ${research.culturalMoments.length})
${playIdGuidance}

Stats will be computed automatically - do not include them.`

          const prompt = Prompt.make([
            {
              role: "system",
              content: systemPrompt,
              options: {
                anthropic: {
                  cacheControl: { type: "ephemeral" }
                }
              }
            },
            { role: "user", content: writerInstructions }
          ])

          const truncatedPrompt = yield* truncatePrompt(prompt, maxTokens, "Writer")
          const chat = yield* Chat.fromPrompt(truncatedPrompt)

          // Token usage
          const tokenUsage = mutableTokenUsage()

          // Generate structured output (no tools needed)
          const response = yield* chat
            .generateObject({
              prompt: [],
              schema: WriterOutputSchema
            })
            .pipe(
              Effect.mapError(e => new SummaryWriterError({
                message: `Failed to generate summary: ${e instanceof Error ? e.message : String(e)}`,
                cause: e
              }))
            )

          // Track token usage
          const usage = response.usage
          if (usage) {
            const input = usage.inputTokens ?? 0
            const output = usage.outputTokens ?? 0
            tokenUsage.inputTokens = input
            tokenUsage.outputTokens = output
            tokenUsage.totalTokens = input + output
          }

          const endTime = yield* Clock.currentTimeMillis
          const durationMs = Number(endTime - startTime)

          // Convert to DailySummary
          const summary = toDailySummary(response.value, research)

          yield* Effect.log(`Writer complete for ${research.date}: ${durationMs}ms`)

          return {
            summary,
            durationMs,
            tokenUsage
          }
        })

      return { write } satisfies SummaryWriterAgentInterface
    })
  }
) {}

// =============================================================================
// Layers
// =============================================================================

/**
 * Live layer for SummaryWriterAgent
 */
export const SummaryWriterAgentLive = SummaryWriterAgent.Default
