/**
 * Summary Writer Agent
 *
 * Phase 2 of the Daily Summary pipeline.
 *
 * This agent synthesizes research findings into a polished daily summary.
 * It has no tool access - it works purely from the ResearchContext.
 *
 * Outputs DailySummary with narrative content and structured sections.
 *
 * @module
 */

import { Effect, Schema, Clock, Data } from "effect"
import { LanguageModel, Chat, Prompt } from "@effect/ai"
import {
  buildWriterSystemPrompt,
  buildResearchContextMessage
} from "./prompts/writer-prompt.js"
import type { ResearchContextType, DailySummaryType } from "./schemas.js"

// =============================================================================
// Types
// =============================================================================

/**
 * Writer agent result including metadata
 */
export interface WriterResult {
  readonly summary: DailySummaryType
  readonly durationMs: number
  readonly tokenUsage: {
    readonly inputTokens: number
    readonly outputTokens: number
    readonly cacheReadTokens: number
    readonly cacheCreationTokens: number
  }
}

/**
 * Error type for writer failures
 */
export class SummaryWriterError extends Data.TaggedError("SummaryWriterError")<{
  readonly message: string
  readonly cause?: unknown
}> {}

// =============================================================================
// Output Schema for LLM
// =============================================================================

/**
 * Schema for writer output
 */
const WriterOutputSchema = Schema.Struct({
  headline: Schema.String,

  // Narrative layer - required
  openingNarrative: Schema.String,

  // All arrays are optional - LLM may omit fields
  highlights: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    playId: Schema.Number,
    headline: Schema.String,
    description: Schema.String,
    category: Schema.Literal("discovery", "theme", "cultural", "connection", "rare", "local"),
    showName: Schema.NullOr(Schema.String)
  })))),

  discoveries: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    playId: Schema.Number,
    artist: Schema.String,
    song: Schema.String,
    album: Schema.NullOr(Schema.String),
    discoveryType: Schema.Literal("first_play", "first_artist", "first_album"),
    blurb: Schema.String
  })))),

  freshReleases: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    playId: Schema.Number,
    artist: Schema.String,
    song: Schema.String,
    album: Schema.NullOr(Schema.String),
    releaseDate: Schema.NullOr(Schema.String),
    releaseType: Schema.Literal("single", "album", "ep", "compilation", "unknown"),
    isLocal: Schema.Boolean,
    blurb: Schema.String
  })))),

  rotationUpdates: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    playId: Schema.Number,
    artist: Schema.String,
    song: Schema.String,
    rotationStatus: Schema.NullOr(Schema.String),
    playCountToday: Schema.Number,
    blurb: Schema.NullOr(Schema.String)
  })))),

  themes: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    title: Schema.String,
    description: Schema.String,
    playIds: Schema.Array(Schema.Number),
    showNames: Schema.Array(Schema.String)
  })))),

  culturalMoments: Schema.optional(Schema.NullOr(Schema.Array(Schema.Struct({
    type: Schema.Literal("birthday", "anniversary", "death", "event", "theme_day", "other"),
    title: Schema.String,
    description: Schema.String,
    playIds: Schema.Array(Schema.Number),
    source: Schema.NullOr(Schema.String)
  })))),

  // Play references - optional
  playIds: Schema.optional(Schema.NullOr(Schema.Array(Schema.Number))),
  topPickIds: Schema.optional(Schema.NullOr(Schema.Array(Schema.Number))),
  newMusicPlaylistIds: Schema.optional(Schema.NullOr(Schema.Array(Schema.Number)))

  // Note: stats are computed from research context, not generated by LLM
})

type WriterOutput = typeof WriterOutputSchema.Type

// =============================================================================
// Service Interface
// =============================================================================

export interface SummaryWriterAgentInterface {
  /**
   * Write summary from research context
   */
  readonly write: (
    research: ResearchContextType
  ) => Effect.Effect<
    WriterResult,
    SummaryWriterError,
    LanguageModel.LanguageModel
  >
}

// =============================================================================
// Service Tag
// =============================================================================

export class SummaryWriterAgent extends Effect.Service<SummaryWriterAgent>()(
  "SummaryWriterAgent",
  {
    effect: Effect.gen(function* () {
      // Token usage tracking
      type TokenUsage = {
        inputTokens: number
        outputTokens: number
        cacheReadTokens: number
        cacheCreationTokens: number
      }

      /**
       * Convert writer output to DailySummary
       *
       * Stats are computed from research context (not LLM-generated) for accuracy.
       */
      const toDailySummary = (
        output: WriterOutput,
        research: ResearchContextType
      ): DailySummaryType => ({
        date: research.date,
        headline: output.headline,

        // Narrative layer
        openingNarrative: output.openingNarrative,
        highlights: (output.highlights ?? []).map(h => ({
          ...h,
          category: h.category as "discovery" | "theme" | "cultural" | "connection" | "rare" | "local"
        })),

        // Structured sections - handle null with empty arrays
        discoveries: (output.discoveries ?? []).map(d => ({
          ...d,
          discoveryType: d.discoveryType as "first_play" | "first_artist" | "first_album"
        })),
        freshReleases: (output.freshReleases ?? []).map(r => ({
          ...r,
          releaseType: r.releaseType as "single" | "album" | "ep" | "compilation" | "unknown"
        })),
        rotationUpdates: output.rotationUpdates ?? [],
        themes: output.themes ?? [],
        culturalMoments: (output.culturalMoments ?? []).map(c => ({
          ...c,
          type: c.type as "birthday" | "anniversary" | "death" | "event" | "theme_day" | "other"
        })),

        // Play references - handle null with empty arrays/null
        playIds: output.playIds ?? [],
        topPickIds: output.topPickIds ?? [],
        newMusicPlaylistIds: output.newMusicPlaylistIds ?? [],

        // Stats - computed from research context for accuracy (not LLM-generated)
        stats: {
          totalPlays: research.totalPlays,
          uniqueArtists: research.uniqueArtists,
          uniqueAlbums: research.uniqueAlbums,
          newToKexp: research.discoveries.length, // Count of discoveries
          localArtists: research.localArtistCount,
          livePerformances: research.livePerformanceCount,
          listenerRequests: research.requestCount,
          showCount: research.showSummaries.length
        },

        // Metadata
        generatedAt: new Date().toISOString(),
        researchId: 0 // Will be set by orchestrator
      })

      const write = (
        research: ResearchContextType
      ): Effect.Effect<
        WriterResult,
        SummaryWriterError,
        LanguageModel.LanguageModel
      > =>
        Effect.gen(function* () {
          yield* Effect.log(`Starting writer for ${research.date}`)

          const startTime = yield* Clock.currentTimeMillis

          // Build prompt using array-based pattern (correct @effect/ai API)
          const systemPrompt = buildWriterSystemPrompt()
          const userMessage = buildResearchContextMessage(research)

          const writerInstructions = `${userMessage}

Write the complete daily summary as JSON. Include:
- A compelling headline
- Opening narrative (2-3 paragraphs)
- 5-8 highlights with play IDs
- All discoveries from the research
- Fresh releases
- Rotation updates
- Themes with representative play IDs
- Cultural moments with associated play IDs
- Complete playIds array (ALL referenced plays)
- topPickIds (5-10 must-hear selections)
- newMusicPlaylistIds (all new music for playlist)

Every play you mention MUST have its play ID included in the playIds array.
Stats will be computed automatically - do not include them.`

          const prompt = Prompt.make([
            {
              role: "system",
              content: systemPrompt,
              options: {
                anthropic: {
                  cacheControl: { type: "ephemeral" }
                }
              }
            },
            { role: "user", content: writerInstructions }
          ])

          const chat = yield* Chat.fromPrompt(prompt)

          // Token usage
          const tokenUsage: TokenUsage = {
            inputTokens: 0,
            outputTokens: 0,
            cacheReadTokens: 0,
            cacheCreationTokens: 0
          }

          // Generate structured output (no tools needed)
          const response = yield* chat
            .generateObject({
              prompt: [],
              schema: WriterOutputSchema
            })
            .pipe(
              Effect.mapError(e => new SummaryWriterError({
                message: `Failed to generate summary: ${e instanceof Error ? e.message : String(e)}`,
                cause: e
              }))
            )

          // Track token usage
          const usage = response.usage
          if (usage) {
            tokenUsage.inputTokens = usage.inputTokens ?? 0
            tokenUsage.outputTokens = usage.outputTokens ?? 0
          }

          const endTime = yield* Clock.currentTimeMillis
          const durationMs = Number(endTime - startTime)

          // Convert to DailySummary
          const summary = toDailySummary(response.value, research)

          yield* Effect.log(`Writer complete for ${research.date}: ${durationMs}ms`)

          return {
            summary,
            durationMs,
            tokenUsage
          }
        })

      return { write } satisfies SummaryWriterAgentInterface
    })
  }
) {}

// =============================================================================
// Layers
// =============================================================================

/**
 * Live layer for SummaryWriterAgent
 */
export const SummaryWriterAgentLive = SummaryWriterAgent.Default
